import { User } from "./types";
import {
  DEPARTMENTS,
  GENDERS,
  USER_ROLES,
  USER_STATUSES,
} from "@/lib/constants";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Ibrahim",
    email: "sarah.ibrahim@example.com",
    phoneNumber: "+233 24 123 4567",
    gender: GENDERS.FEMALE,
    username: "sarah.ibrahim",
    role: USER_ROLES.ADMIN,
    department: DEPARTMENTS.CRIME_JUSTICE,
    status: USER_STATUSES.ACTIVE,
    avatarUrl: "https://i.pravatar.cc/150?u=sarah",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john.doe@example.com",
    phoneNumber: "+233 24 987 6543",
    gender: GENDERS.MALE,
    username: "john.doe",
    role: USER_ROLES.EDITOR,
    department: DEPARTMENTS.SPORTS_RECREATION,
    status: USER_STATUSES.ACTIVE,
    avatarUrl: "https://i.pravatar.cc/150?u=john",
  },
  {
    id: "3",
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    phoneNumber: "+233 24 456 7890",
    gender: GENDERS.FEMALE,
    username: "emma.wilson",
    role: USER_ROLES.REPORTER,
    department: DEPARTMENTS.EDUCATION_RESEARCH,
    status: USER_STATUSES.PENDING,
    avatarUrl: "https://i.pravatar.cc/150?u=emma",
  },
  {
    id: "4",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    role: USER_ROLES.VIEWER,
    department: DEPARTMENTS.CRIME_JUSTICE,
    status: USER_STATUSES.INACTIVE,
    avatarUrl: "https://i.pravatar.cc/150?u=michael",
    phoneNumber: "+233 24 123 4567",
    gender: GENDERS.MALE,
    username: "michael.chen",
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.anderson@example.com",
    role: USER_ROLES.EDITOR,
    department: DEPARTMENTS.EDUCATION_RESEARCH,
    status: USER_STATUSES.ACTIVE,
    avatarUrl: "https://i.pravatar.cc/150?u=lisa",
    phoneNumber: "+233 24 123 4567",
    gender: GENDERS.FEMALE,
    username: "lisa.anderson",
  },
];
